experiment_name: "simclr_resnet50_stl10_base"
seed: 42

dataset:
  image_size: 96
  batch_size: 1024
  num_workers: 16
  root_dir: "data/stl10"

model:
  out_dim: 128

training:
  epochs: 650
  lr: 0.6
  min_lr: 0.000001
  weight_decay: 0.000001
  temperature: 0.1
  resume_checkpoint: null
  save_dir: "checkpoints"
  log_dir: "runs"

linear_eval:
  epochs: 100
  batch_size: 128
  lr: 0.1
  weight_decay: 0.0001
  num_workers: 4
  min_lr: 0.000001

knn_eval:
  k: 20
